### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by gthieleb** [seidler2547/home-assistant-cc#1]
I've succeeded using your sygonix module to work with current ha and euronics comet blue thermostat.

A fix was required as current ha climate module misses `PRECISION_HALF` and needs a `supported_feature` property. Do you except pull request for this?

Thanks for your great work!

**Comment by seidler2547** [comment]
Yes, although I have completely rewritten the module to use a Bluetooth to MQTT bridge. Your changes might still be relevant for the new module.

Background: the thermostats send out beacons in regular intervals reporting most of the important data like set and measured temperature, operating mode and battery level. Since listening to BT broadcasts requires root and I did not want to run HA as root, I wrote the BTLE-to-MQTT bridge and rewrote this module to use MQTT.

**Comment by animavitis** [comment]
Hi,

@seidler2547 can u share with us your BTLE-to-MQTT bridge??

**Comment by gthieleb** [comment]
@seidler2547 Do you think  ble/mqtt Code will fit in same module? Otherwise i would split code in sygonix_ble sygonix_mqtt. Is root really  necessary when capabilities like in [1] are set? Do you already have support to toggle between auto and manual mode?

**Comment by seidler2547** [comment]
Updated and shared to Bridge at https://github.com/seidler2547/ble-mqtt-bridge

I haven't updated my HA instance in a long time, so if you make this work the most recent HA, I would be grateful for a PR.

Been running this code for over a year without any problems, except those that are related to the bad implementation of the devices, e.g. the Progtime switch sometimes crashes and needs to be unplugged for some seconds to work again. The thermostats work fine.

**Comment by seidler2547** [comment]
@gthieleb the problem isn't only the root permissions. It's also that if you have 8 thermostats and try to set the temp for some of them, the Bluetooth stack will likely collapse. The MQTT bridge is a very simple piece of code that solves all the problems of concurrency and queuing (naturally) of the "native" bluepy method. Especially since the async nature of MQTT and HA fits very well with the BT LE API, which is also heavily based on callbacks etc.

**Comment by gthieleb** [comment]
@seidler2547 sound reasonable. I wasn't aware that writing mqtt broker is that easy with python. I'll have a little learning curve understanding the code, especially the `ThreadPoolExecutor`.  
Would you mind posting your HA mqtt config? Do you have that script running local next to HA? One note about about python Thread. I would start the thread outside its __init__ method.


	def main():

		thread = CommandThread()
		thread.start()

		while True:
			time.sleep(1)

	if __name__ == '__main__':
		main()

**Comment by seidler2547** [comment]
Thanks for the Python comment. I don't have a clue about Python as you can see :-)

This is not a broker, only a MQTT client. HA config just points to localhost. I installed mosquitto using `apt-get` , nothing more.

**Comment by animavitis** [comment]
@gthieleb I run HASS from docker, and ble-to-mqtt is running on docker host machine.
HASS mqtt sygonix config:

> climate:
>   - platform: sygonix
>     devices:
>       room1:
>         mac: a5:80:bc:ca:66:b2
>         pin: 123456


for me its works only for reading configuration & temps from comet blue, sadly setting new temp or changing operating state is not:/. I always get same error in ble-mqtt-bridge:

> Connecting to a5:80:bc::ba:a6:b2
>  Connected to a5:80:bc:ba:a6:b2
>   Command {'action': 'writeCharacteristic', 'handle': 71, 'value': [64, 226, 1, 0]}
>     Write b'@\xe2\x01\x00' to 71
> Waiting...
> Error: Error from Bluetooth stack (comerr)

**Comment by seidler2547** [comment]
Updated the code to work with HA 0.63

**Comment by Melcos1970** [comment]
Please somebody make a step-by-step tutorial to get this work in HASSIO on raspberry pi. 
This is genius, but i am not.. Can't get i to work.. Anybody ??
